blog/urls.py
from django.urls import path

from blog import views as blog_views

urlpatterns = [
    path('', blog_views.home_page, name='home'),
]

blog_django/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog_django import views as blog_views

urlpatterns = [
    path('', blog_views.home_page, name='home'),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

# TODO: Test in staging what happens to the url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'
urlpatterns = [
    path('create', views.create, name='create'),
    path('store', views.store, name='store'),
    path('show/<int:post_id>/', views.show, name='show'),
    path('index/', views.index, name='index'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
    path('update/<int:post_id>/', views.update, name='update'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('ajax_publication_date/<int:post_id>/', views.ajax_publication_date, name='ajax_publication_date'),
]

blog_django/views.py
import datetime

from django.shortcuts import render, redirect
from posts.models import Post

def home_page(request):
    today = datetime.date.today()
    posts = Post.objects.filter(expiring_date__gte=today,
                                publication_date__lte=today)
    return render(request, 'blog_django/home.html', {'posts':  posts})

blog_django/templates/blog_django/home.html
{% extends 'base.html' %}

{% block title %}Blog Django{% endblock %}

{% block header_text %}Blog Django{% endblock %}

{% block header_paragraph %}
  <p class="lead lead-lg color-white text-center center-block mt-2 mw-800 fw-300 animated fadeInUp animation-delay-7">Follow our blog and discover the latest content and trends in the market. In addition you will discover the best
    <span class="colorStar">tricks</span> and
    <span class="colorStar">discounts</span>.</p>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      {% for post in posts %}
        <article class="card card-primary wow zoomInRight animation-delay-5 mb-4">
          <div class="card-block card-block-big">
            <div class="row">
              <div class="col-lg-6">
                {% if post.image %}
                  <img src="{{ post.image.url }}" alt="" class="img-responsive mb-4"> </div>
                {% endif %}
              <div class="col-lg-6 mb-4">
                <h3 class="no-mt">
                  <a href="javascript:void(0)">{{ post.title }}</a>
                </h3>
                <p>{{ post.content | truncatechars:100 }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-8">
                <span class="ml-1 hidden-xs">
                  <i class="zmdi zmdi-time mr-05 color-info"></i>
                  <span class="color-medium-dark">{{ post.publication_date }}</span>
                </span>
              </div>
              <div class="col-lg-4 text-right">
                <a href="{% url 'posts:show' post.id %}" class="btn btn-primary btn-raised btn-block animate-icon">Read More
                  <i class="ml-1 no-mr zmdi zmdi-long-arrow-right"></i>
                </a>
              </div>
            </div>
          </div>
        </article>
      {% endfor %}
    </div>
  </div>
{% endblock%}