blog/urls.py
from django.urls import path

from blog import views as blog_views

urlpatterns = [
    path('', blog_views.home_page, name='home'),
]

blog_django/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog_django import views as blog_views

urlpatterns = [
    path('', blog_views.home_page, name='home'),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

# TODO: Test in staging what happens to the url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'
urlpatterns = [
    path('create', views.create, name='create'),
    path('store', views.store, name='store'),
    path('show/<int:post_id>/', views.show, name='show'),
    path('index/', views.index, name='index'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
    path('update/<int:post_id>/', views.update, name='update'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('ajax_publication_date/<int:post_id>/', views.ajax_publication_date, name='ajax_publication_date'),
]

posts/models.py
import datetime

from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    # TODO: put the required in image.
    image = models.ImageField(blank=True, null=True)
    publication_date = models.DateField()
    expiring_date = models.DateField()

    def __str__(self):
        data = {
            'title': self.title,
            'content': self.content,
            'image': self.image,
            'publication_date': self.publication_date,
            'expiring_date': self.expiring_date,
        }
        return repr(data)

posts/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError

from posts.models import Post

EXPIRATION_DATE_IS_WRONG = 'The expiring date needs to be after the publication date.'

class PostForm(forms.models.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        exclude = []
        widgets = {
            'title': forms.fields.TextInput(attrs={
                'class': 'form-control'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control'
            }),
            'image': forms.fields.FileInput(attrs={
                'class': 'form-control'
            }),
            'publication_date': forms.fields.DateInput(attrs={
                'input_type': 'date',
                'class': 'form-control'
            }),
            'expiring_date': forms.fields.DateInput(attrs={
                'input_type': 'date',
                'class': 'form-control'
            }),
        }

    def clean(self):
        expiring_date = self.cleaned_data.get('expiring_date')
        publication_date = self.cleaned_data.get('publication_date')
        if publication_date == None or expiring_date == None:
            pass
        elif publication_date > expiring_date:
            self._errors['expiring_date'] = [EXPIRATION_DATE_IS_WRONG]
        return self.cleaned_data

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.http import JsonResponse

from posts.forms import PostForm
from posts.models import Post

def create(request):
    form = PostForm()
    return render(request, 'posts/create.html', {'form': form})


def store(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, 'The blog post has been created')
            return redirect(reverse('posts:show', kwargs={'post_id': post.id}))
        return render(request, 'posts/create.html', {'form': form})


def show(request,  post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'posts/show.html', {'post': post})


def index(request):
    posts = Post.objects.all()
    return render(request, 'posts/index.html', {'posts': posts})


def edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(instance=post)
    return render(request, 'posts/edit.html', {'form': form})


def update(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, 'The blog post has been updated')
            return redirect(reverse('posts:show', kwargs={'post_id': post.id}))
        return render(request, 'posts/edit.html', {'form': form})


def delete(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        post.delete()
        messages.success(request, 'The blog post has been succesfully deleted')
        return redirect(reverse('posts:index'))


def ajax_publication_date(request, post_id):
    if request.is_ajax():
        post = get_object_or_404(Post, id=post_id)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            data = {
                'message' : 'The publication date has been saved.'
            }
        else:
            publication_date_errors = form.errors.get('publication_date')
            if publication_date_errors == None:
                data = {
                    'message' : 'The publication date has not been saved.'
                }
            else:
                data = {
                    'message' : form.errors['publication_date'][0]
                }
        return JsonResponse(data)

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/jquery-ui.css" />
{% endblock %}

{% block title %}Blog Django | Create New Post{% endblock %}

{% block header_text %}Create New Post{% endblock %}

{% block content %}
  <div class="row">
      <div class="col-md-12">
        <div class="card animated materialU animation-delay-5">
          <div class="card-block card-block-big">
            <form action="{% url 'posts:store' %}" method="post" enctype='multipart/form-data'>
              {{ form }}
              <input type="submit" name="create post" value="Create post" class="btn btn-success">
              {% csrf_token %}
            </form>
          </div>
        </div>
    </div>
  </div>

{% endblock %}

{% block scripts %}
<script src="/static/js/jquery-ui.js"></script>
<script>
$("#id_publication_date").change(function(){
  time_of_publication_date = $( "#id_publication_date" ).datepicker("getDate").getTime();
  $( "#id_expiring_date" ).datepicker( "option", "minDate", new Date(time_of_publication_date) );
} );

$(document).ready( function() {

  var publication_date = $("#id_publication_date").val()
  $( "#id_publication_date" ).datepicker();
  $( "#id_publication_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
  $( "#id_publication_date" ).val(publication_date)

  var expiration_date = $( "#id_expiring_date" ).val()
  $( "#id_expiring_date" ).datepicker();
  $( "#id_expiring_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
  $( "#id_expiring_date" ).val(expiration_date)
} );
</script>

{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/jquery-ui.css" />
{% endblock %}

{% block title %}Blog Django | Edit Post{% endblock %}

{% block header_text %}Edit Post{% endblock %}

{% block content %}
  <div class="row">
      <div class="col-md-12">
        <div class="card animated materialU animation-delay-5">
          <div class="card-block card-block-big">
            <form action="{% url 'posts:update' form.instance.id %}" method="post" enctype='multipart/form-data'>
              {{ form }}
              <input type="submit" name="save changes" value="Save Changes" class="btn btn-success">
              {% csrf_token %}
            </form>
          </div>
        </div>
    </div>
  </div>

{% endblock %}

{% block scripts %}
<script src="/static/js/jquery-ui.js"></script>
<script>
$("#id_publication_date").change(function(){
  time_of_publication_date = $( "#id_publication_date" ).datepicker("getDate").getTime();
  $( "#id_expiring_date" ).datepicker( "option", "minDate", new Date(time_of_publication_date) );

  $.ajax({
    url: "{% url 'posts:ajax_publication_date' form.instance.id %}",
    data: $("form").serialize(),
    cache: false,
    type: 'post',
    success: function (data) {
      $("#messages").html(`<div  class='alert alert-success'> ${data.message} </div>`);
      // $("#add_category .modal-body").html(data);
    }
  });
  
} );

$(document).ready( function() {

  var publication_date = $("#id_publication_date").val()
  $( "#id_publication_date" ).datepicker();
  $( "#id_publication_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
  $( "#id_publication_date" ).val(publication_date)

  var expiration_date = $( "#id_expiring_date" ).val()
  $( "#id_expiring_date" ).datepicker();
  $( "#id_expiring_date" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
  $( "#id_expiring_date" ).val(expiration_date)
} );
</script>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Blog Django | Posts Index {% endblock %}

{% block header_text %}All Posts{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      {% for post in posts %}
        <article class="card card-primary wow zoomInRight animation-delay-5 mb-4">
          <div class="card-block card-block-big">
            <div class="row">
              <div class="col-lg-6">
                {% if post.image %}
                  <img src="{{ post.image.url }}" alt="" class="img-responsive mb-4"> </div>
                {% endif %}
              <div class="col-lg-6 mb-4">
                <h3 class="no-mt">
                  <a href="javascript:void(0)">{{ post.title }}</a>
                </h3>
                <p>{{ post.content | truncatechars:100 }}</p>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-8">
                <span class="ml-1 hidden-xs">
                  <i class="zmdi zmdi-time mr-05 color-info"></i>
                  <span class="color-medium-dark">{{ post.publication_date }}</span>
                </span>
              </div>
              <div class="col-lg-4 text-right">
                <a href="{% url 'posts:show' post.id %}" class="btn btn-primary btn-raised btn-block animate-icon">Read More
                  <i class="ml-1 no-mr zmdi zmdi-long-arrow-right"></i>
                </a>
                <a href="{% url 'posts:edit' post.id %}" class="btn btn-success btn-raised btn-block animate-icon">Edit Post
                  <i class="ml-1 no-mr zmdi zmdi-long-arrow-right"></i>
                </a>
                <form action="{% url 'posts:delete' post.id %}" method="post">
                  <input type="submit" value="Delete Post" name="delete post" class="btn btn-danger btn-raised btn-block animate-icon">
                  {% csrf_token %}
                </form>
              </div>
            </div>
          </div>
        </article>
      {% endfor %}
    </div>
  </div>
{% endblock%}

posts/templates/posts/show.html
{% extends 'base.html' %}

{% block title %}Blog Django | View Blog Post{% endblock %}

{% block header_text %}View Blog Post{% endblock %}

{% block content %}
  <div class="row">
      <div class="col-md-12">
        <div class="card animated materialU animation-delay-5">
          <div class="card-block card-block-big">
            <h1 class="no-mt ">{{ post.title }}</h1>
            <div class="mb-4 ">
                <span class="ml-1 hidden-xs ">
                  <i class="zmdi zmdi-time mr-05 color-info ">
                  </i>
                  <span class="color-medium-dark ">{{ post.publication_date|date:"M. d, Y" }}
                  </span>
                </span>
                <span class="ml-1 hidden-xs ">
                  <i class="zmdi zmdi-time mr-05 color-danger ">
                  </i>
                  <span class="color-medium-dark ">{{ post.expiring_date|date:"M. d, Y" }}
                  </span>
                </span>
            </div>
            {% if post.image %}
              <img src="{{ post.image.url }}" alt=" " class="img-responsive mb-4">
            {% endif %}
            <p>{{ post.content }}</p>
          </div>
        </div>
    </div>
  </div>

{% endblock %}